### ISSUE TITLE
sacreBLEU silently fails on some systems (such as Red Hat scientific linux)

### ISSUE THREAD

**Issue by XapaJIaMnu** [mjpost/sacreBLEU#17]
Hey,

sacreBLEU silently produces very short files on some systems. I believe it is some sort of locale issue, but I am not exactly sure what's happening. Here's an example:
```bash
[cs-bogo1@login-e-6 sacretest]$ LC_ALL=C.UTF-8 ../sacreBLEU/sacrebleu.py -t wmt13 -l en-de --echo ref > testvalid.de
[cs-bogo1@login-e-6 sacretest]$ LC_ALL=C.UTF-8 ../sacreBLEU/sacrebleu.py -t wmt13 -l en-de --echo src > testvalid.en
[cs-bogo1@login-e-6 sacretest]$ wc -l *
   1 testvalid.de
  70 testvalid.en
  71 total
[cs-bogo1@login-e-6 sacretest]$ rm -rf *
[cs-bogo1@login-e-6 sacretest]$ ../sacreBLEU/sacrebleu.py -t wmt13 -l en-de --echo ref > testvalid.de
[cs-bogo1@login-e-6 sacretest]$ ../sacreBLEU/sacrebleu.py -t wmt13 -l en-de --echo src > testvalid.en
[cs-bogo1@login-e-6 sacretest]$ wc -l *
   1 testvalid.de
  70 testvalid.en
  71 total
```

This happens on a number of systems and I am unable to find a pattern as of yet. My affected system has the following python version: 
Python 3.6.4 (default, Jan 18 2018, 00:44:15) 
[GCC 5.4.0] on linux
My working system has the following python version:
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux

At the very least there should be an error and not a silent failure.

Cheers,

Nick

**Comment by emjotde** [comment]
I have the same issue, but I tracked it halfway down. It's not a locale problem, it's a programming error. For some reason, args.metric is now a string, not a list. While the final look loops through metrics in line 1379 it actually loops through ['b','l','e','u'] instead of ["bleu"], hence no metric matches and no output.

**Comment by emjotde** [comment]
Works if `--metrics bleu` is specified by hand.

**Comment by XapaJIaMnu** [comment]
I think I am experiencing a different issue `--metrics bleu` doesn't work for me. 
For me some datasets work, if the locale is not specified, but crash if it is: eg wmt17 reference. Source doesn't work either way:
```bash
[cs-bogo1@login-e-6 sacretest]$ ../sacreBLEU/sacrebleu.py -t wmt17 -l en-de --echo ref > testvalid.de
[cs-bogo1@login-e-6 sacretest]$ ../sacreBLEU/sacrebleu.py -t wmt17 -l en-de --echo src > testvalid.en
[cs-bogo1@login-e-6 sacretest]$ wc -l *
  3004 testvalid.de
    47 testvalid.en
  3051 total
[cs-bogo1@login-e-6 sacretest]$ LC_ALL=C.UTF-8 ../sacreBLEU/sacrebleu.py -t wmt17 -l en-de --echo ref > testvalid.de
Traceback (most recent call last):
  File "../sacreBLEU/sacrebleu.py", line 1399, in <module>
    main()
  File "../sacreBLEU/sacrebleu.py", line 1333, in main
    print_test_set(args.test_set, args.langpair, args.echo)
  File "../sacreBLEU/sacrebleu.py", line 957, in print_test_set
    for line in fin:
  File "/home/cs-bogo1/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
[cs-bogo1@login-e-6 sacretest]$ LC_ALL=C.UTF-8 ../sacreBLEU/sacrebleu.py -t wmt17 -l en-de --echo src > testvalid.en
[cs-bogo1@login-e-6 sacretest]$ wc -l *
   0 testvalid.de
  47 testvalid.en
  47 total
```
That being said, the locale might be broken on my system:
```bash
[cs-bogo1@login-e-6 sacretest]$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
[cs-bogo1@login-e-6 sacretest]$ LC_ALL=C.UTF-8 locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_GB.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=C.UTF-8
```

**Comment by emjotde** [comment]
Another example why I consider dependency on locale a bug :)

**Comment by mjpost** [comment]
Ack, sorry about the error. I somehow forgot to run the regression tests.

This is now fixed in 1.23. I believe I have also fixed the locale issue by explicitly setting it for sys.stdin.

**Comment by XapaJIaMnu** [comment]
This is not fixed. Experiencing exactly the same issue on the HPC cluster I am using. Same crashes on some datasets, same incomplete productions on others...

**Comment by mjpost** [comment]
Hi, can you tell me what version of

**Comment by XapaJIaMnu** [comment]
I'm using a clone of master as of today:
git clone https://github.com/mjpost/sacreBLEU -b master
python 3.6.4
Distributor ID: Scientific
Description:    Scientific Linux release 7.4 (Nitrogen)
Release:        7.4
Codename:       Nitrogen

**Comment by mjpost** [comment]
Okay. If you can send me the command you typed, the error messages you get, and ideally share a test output, I can help diagnose it.

**Comment by XapaJIaMnu** [comment]
Hey,
Here's an example of a problematic dataset (wmt17) the files that are produced and the commands I used:
```bash
[cs-bogo1@login-e-6 transformer_sync_batchflex]$ ../tools/sacreBLEU/sacrebleu.py -t wmt17 -l en-de --echo src > test2017.en.noutf 
[cs-bogo1@login-e-6 transformer_sync_batchflex]$ ../tools/sacreBLEU/sacrebleu.py -t wmt17 -l en-de --echo ref > test2017.de.noutf 
[cs-bogo1@login-e-6 transformer_sync_batchflex]$ wc -l test2017.en.noutf
47 test2017.en.noutf
[cs-bogo1@login-e-6 transformer_sync_batchflex]$ wc -l test2017.de.noutf
3004 test2017.de.noutf
[cs-bogo1@login-e-6 transformer_sync_batchflex]$ LC_ALL=C.UTF-8 ../tools/sacreBLEU/sacrebleu.py -t wmt17 -l en-de --echo ref > test2017.de.utf 
Traceback (most recent call last):
  File "../tools/sacreBLEU/sacrebleu.py", line 1434, in <module>
    main()
  File "../tools/sacreBLEU/sacrebleu.py", line 1368, in main
    print_test_set(args.test_set, args.langpair, args.echo)
  File "../tools/sacreBLEU/sacrebleu.py", line 989, in print_test_set
    print('\t'.join(map(lambda x: x.rstrip(), lines)))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 4: ordinal not in range(128)
[cs-bogo1@login-e-6 transformer_sync_batchflex]$ LC_ALL=C.UTF-8 ../tools/sacreBLEU/sacrebleu.py -t wmt17 -l en-de --echo src > test2017.en.utf 
[cs-bogo1@login-e-6 transformer_sync_batchflex]$ wc -l *.utf
   0 test2017.de.utf
  47 test2017.en.utf
  47 total
[cs-bogo1@login-e-6 transformer_sync_batchflex]$ wc -l *.noutf
   154 test2016.en.noutf
  3004 test2017.de.noutf
    47 test2017.en.noutf
  3205 total
```
If I force the UTF locale I get crashes in some cases, others are fine. Here are the output files of the commands above:
https://nbogoychev.com/files/files.tar.gz

**Comment by mjpost** [comment]
I'm guessing the failure for test2017.en.noutf is a corrupted cache. Try

    rm ~/.sacrebleu/wmt17/en-de.*

and rerun.

**Comment by mjpost** [comment]
The good news is that I can reproduce your other error. These UTF-8 problems with Python (not just sacrebleu) are a real pain. Let me look a minute.

**Comment by mjpost** [comment]
I pushed a possible fix to a `utf-8` branch. I tested it a bit but not too extensively. Can you try it out?

**Comment by XapaJIaMnu** [comment]
Hey,

Thanks for looking into that. Indeed clearing the cache fixes the problem. However if I try manually set the locale prior to generating the dataset I get weird crashes of the sort:
```bash
Traceback (most recent call last):
  File "../tools/sacreBLEU/sacrebleu.py", line 1434, in <module>
    main()
  File "../tools/sacreBLEU/sacrebleu.py", line 1368, in main
    print_test_set(args.test_set, args.langpair, args.echo)
  File "../tools/sacreBLEU/sacrebleu.py", line 989, in print_test_set
    print('\t'.join(map(lambda x: x.rstrip(), lines)))
UnicodeEncodeError: 'ascii' codec can't encode character '\xdf' in position 102: ordinal not in range(128)
```
In general should locale be manually set or not prior to running sacreBLEU?

Cheers,

Nick

**Comment by XapaJIaMnu** [comment]
Hey, I just tried the utf-8 branch. Same errors
```
sacreBLEU: Processing /home/cs-bogo1/.sacrebleu/wmt15/raw/test/newstest2015-ende-ref.de.sgm to /home/cs-bogo1/.sacrebleu/wmt15/en-de.de
Traceback (most recent call last):
  File "../tools/sacreBLEU/sacrebleu.py", line 1434, in <module>
    main()
  File "../tools/sacreBLEU/sacrebleu.py", line 1368, in main
    print_test_set(args.test_set, args.langpair, args.echo)
  File "../tools/sacreBLEU/sacrebleu.py", line 989, in print_test_set
    print('\t'.join(map(lambda x: x.rstrip(), lines)))
UnicodeEncodeError: 'ascii' codec can't encode character '\xa3' in position 231: ordinal not in range(128)
[cs-bogo1@login-e-6 transformer_sync_batchflex]$     LC_ALL=C.UTF-8 ../tools/sacreBLEU/sacrebleu.py -t wmt16 -l en-de --echo src > data/test2016.en  
sacreBLEU: Creating /home/cs-bogo1/.sacrebleu/wmt16
sacreBLEU: Downloading http://data.statmt.org/wmt16/translation-task/test.tgz to /home/cs-bogo1/.sacrebleu/wmt16/test.tgz
sacreBLEU: Extracting /home/cs-bogo1/.sacrebleu/wmt16/test.tgz
sacreBLEU: Processing /home/cs-bogo1/.sacrebleu/wmt16/raw/test/newstest2016-ende-src.en.sgm to /home/cs-bogo1/.sacrebleu/wmt16/en-de.en
sacreBLEU: Processing /home/cs-bogo1/.sacrebleu/wmt16/raw/test/newstest2016-ende-ref.de.sgm to /home/cs-bogo1/.sacrebleu/wmt16/en-de.de
Traceback (most recent call last):
  File "../tools/sacreBLEU/sacrebleu.py", line 1434, in <module>
    main()
  File "../tools/sacreBLEU/sacrebleu.py", line 1368, in main
    print_test_set(args.test_set, args.langpair, args.echo)
  File "../tools/sacreBLEU/sacrebleu.py", line 989, in print_test_set
    print('\t'.join(map(lambda x: x.rstrip(), lines)))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 76: ordinal not in range(128)
```

In general, should one just not set a locale?

Cheers,

Nick

**Comment by mjpost** [comment]
Hi, sorry — I created the utf-8 branch, but then forgot to commit my change. Can you pull and try again? It should work now.

The goal is that sacrebleu should not depend at all on the locale. However, these issues keep popping up as new utf-8 leaks are found. Python 3 has better UTF-8 support than Python 2 but there are still lots of problems.

**Comment by XapaJIaMnu** [comment]
Yes, your utf-8 branch doesn't crash and produces the correct output.
Also maybe there should be some checksumming in case of corrupted cache?

**Comment by mjpost** [comment]
Glad to hear it! I'll fold this in after I test it some more.

Yes, agreed, checksumming would be great. Care to add it? :)

**Comment by mjpost** [comment]
Okay, this has been pulled in and pushed out under release 1.2.7 (`pip3 install -U sacrebleu`). Closing for now. Thanks for your input!
