### ISSUE TITLE
wmt17/dev  checksum failed

### ISSUE THREAD

**Issue by xutaatmicrosoftdotcom** [mjpost/sacreBLEU#21]
Hi,
When I testing the zh-en translation on wmt17 dev file, 

cat my_file |  sacrebleu -t wmt17/dev -l zh-en  

it says: checksum failed. I rerun multiple times, it is the same problem.
Could you please help check this problem?

sacreBLEU: Downloading http://data.statmt.org/wmt17/translation-task/dev.tgz to /var/storage/shared/sdrgvc/sys/jobs/application_1545092712078_50932/.sacrebleu/wmt17/dev/dev.tgz
sacreBLEU: Fatal: MD5 sum of downloaded file was incorrect (got 9b1aa63c1cf49dccdd20b962fe313989, expected 4a3dc2760bb077f4308cce96b06e6af6).
sacreBLEU: Please manually delete "/var/storage/shared/sdrgvc/sys/jobs/application_1545092712078_50932/.sacrebleu/wmt17/dev/dev.tgz" and rerun the command.
sacreBLEU: If the problem persists, the tarball may have changed, in which case, please contact the SacreBLEU maintainer.

**Comment by mjpost** [comment]
Thanks. I just pushed [a fix to this](https://github.com/mjpost/sacreBLEU/commit/0ef2523539edc2e56b77553dfe5f41c4d19a0851). The problem was a copy-paste error. You can pull from this repo or run `pip3 install -U sacrebleu` to upgrade to version 1.2.18.

**Comment by xutaatmicrosoftdotcom** [comment]
Thanks. Now wmt17/dev is correct now, but wmt19/dev still faces this problem.

pip install -U sacrebleu
cat result.txt | sacrebleu -t wmt19/dev -l lt-en

It shows the same error: checksum failed.

Could you help to fix again?

**Comment by mjpost** [comment]
It appears the tarball was updated, though I'm not sure with what. This is fixed with sacrebleu 1.2.19 (just pushed).
